-- CLEAN UP ANTES DE INICIAR A CRIAÇÃO DE TABELAS, COMEÇANDO PELAS FOLHAS
DROP TABLE TF_JOGOS;
DROP TABLE TF_JOGADORES;
DROP TABLE TF_TIMES;
DROP TABLE TF_CIDADES;
DROP TABLE TF_ESTADOS;

-- ESTADOS
CREATE TABLE TF_ESTADOS
(
   ID_ESTADO NUMBER (2) NOT NULL,
   NOME VARCHAR (50) NOT NULL,
   SIGLA VARCHAR (2) NOT NULL CHECK(LENGTH(SIGLA) = 2),
   REGIAO VARCHAR (20) NOT NULL CHECK (REGIAO IN ('NORTE', 'NORDESTE', 'SUL', 'SUDESTE', 'CENTRO-OESTE')),

   CONSTRAINT PK_TF_ESTADOS PRIMARY KEY (ID_ESTADO),
   CONSTRAINT AK1_TF_ESTADOS UNIQUE (NOME),
   CONSTRAINT AK2_TF_ESTADOS UNIQUE (SIGLA)
);

-- CIDADES
CREATE TABLE TF_CIDADES
(
   ID_CIDADE NUMBER (4) NOT NULL,
   NOME VARCHAR (50) NOT NULL,
   ID_ESTADO NUMBER (2) NOT NULL,
   DATA_FUNDACAO DATE NOT NULL,
   REGIAO VARCHAR (20) NOT NULL CHECK (REGIAO IN ('CAPITAL', 'INTERIOR', 'CAMPANHA', 'SERRA', 'LITORAL')),

   CONSTRAINT PK_TF_CIDADES PRIMARY KEY (ID_CIDADE),
   CONSTRAINT FK_CID_EST FOREIGN KEY (ID_ESTADO) REFERENCES TF_ESTADOS (ID_ESTADO)
);

-- TIMES
CREATE TABLE TF_TIMES
(
   ID_TIME NUMBER (3) NOT NULL,
   NOME VARCHAR (50) NOT NULL,
   ID_CIDADE NUMBER (4) NOT NULL,
   DATA_FUNDACAO DATE NOT NULL,
   TECNICO VARCHAR (20) NOT NULL,

   CONSTRAINT PK_TF_TIMES PRIMARY KEY (ID_TIME),
   CONSTRAINT AK_TF_TIMES UNIQUE (NOME),
   CONSTRAINT FK_TIMES_CID FOREIGN KEY (ID_CIDADE) REFERENCES TF_CIDADES (ID_CIDADE)
);

-- JOGADORES
CREATE TABLE TF_JOGADORES
(
   ID_JOGADOR NUMBER (5) NOT NULL,
   NOME VARCHAR (100) NOT NULL,
   DATA_NASCIMENTO DATE NOT NULL,
   ID_TIME NUMBER (2) NOT NULL,
   POSICAO VARCHAR (20) NOT NULL,
   ID_CIDADE_NASCIMENTO NUMBER (4),

   CONSTRAINT PK_JOGADORES PRIMARY KEY (ID_JOGADOR),
   CONSTRAINT FK_JOGADORES_TIME FOREIGN KEY (ID_TIME) REFERENCES TF_TIMES (ID_TIME),
   CONSTRAINT FK_JOGADORES_CIDADE FOREIGN KEY (ID_CIDADE_NASCIMENTO) REFERENCES TF_CIDADES (ID_CIDADE)
);

-- JOGOS
CREATE TABLE TF_JOGOS
(
   ID_JOGO NUMBER (8) NOT NULL,
   ID_MANDANTE NUMBER (3) NOT NULL,
   GOLS_MANDANTE NUMBER (2) NOT NULL,
   ID_VISITANTE NUMBER (3) NOT NULL,
   GOLS_VISITANTE NUMBER (2) NOT NULL,
   DATA_JOGO DATE NOT NULL,
   ID_VENCEDOR NUMBER (3), -- SE ID_VENCEDOR É NULL => EMPATE

   CONSTRAINT PK_JOGOS PRIMARY KEY (ID_JOGO),
   CONSTRAINT FK_JOGOS_TIME1 FOREIGN KEY (ID_MANDANTE) REFERENCES TF_TIMES (ID_TIME),
   CONSTRAINT FK_JOGOS_TIME2 FOREIGN KEY (ID_VISITANTE) REFERENCES TF_TIMES (ID_TIME),
   CONSTRAINT FK_JOGOS_VENC FOREIGN KEY (ID_VENCEDOR) REFERENCES TF_TIMES (ID_TIME)
);
