-- ESTADOS
CREATE TABLE TF_ESTADOS
(
   ID_ESTADO NUMBER (2) NOT NULL,
   NOME VARCHAR (50) NOT NULL,
   SIGLA CHAR (2) NOT NULL,
   REGIAO VARCHAR (20) NOT NULL CHECK (REGIAO IN ('NORTE', 'NORDESTE', 'SUL', 'SUDESTE', 'CENTRO OESTE')),
   
   CONSTRAINT PK_TF_ESTADOS PRIMARY KEY (ID_ESTADO),
   CONSTRAINT AK1_TF_ESTADOS UNIQUE (NOME),
   CONSTRAINT AK2_TF_ESTADOS UNIQUE (SIGLA)
)

INSERT INTO TF_ESTADOS VALUES (1, 'RIO GRANDE DO SUL', 'BR', 'SUL');
INSERT INTO TF_ESTADOS VALUES (2, 'SAO PAULO', 'BR', 'SUDESTE');
INSERT INTO TF_ESTADOS VALUES (3, 'GOIAS', 'BR', 'CENTRO OESTE');
INSERT INTO TF_ESTADOS VALUES (4, 'BAHIA', 'BR', 'NORDESTE');
INSERT INTO TF_ESTADOS VALUES (5, 'PARA', 'BR', 'NORTE');

select * from TF_ESTADOS
order by ID_ESTADO;


-- CIDADES
CREATE TABLE TF_CIDADES 
(
   ID_CIDADE NUMBER (2) NOT NULL,
   NOME VARCHAR (50) NOT NULL,
   ID_ESTADO NUMBER (2) NOT NULL,
   DATA_FUNDACAO DATE NOT NULL,
   REGIAO VARCHAR (20) NOT NULL CHECK (REGIAO IN ('CAPITAL', 'INTERIOR', 'CAMPANHA', 'SERRA', 'LITORAL')),
   
   CONSTRAINT PK_TF_CIDADES PRIMARY KEY (ID_CIDADE),
   CONSTRAINT FK_CID_EST FOREIGN KEY (ID_ESTADO) REFERENCES TF_ESTADOS (ID_ESTADO)
)

INSERT INTO TF_CIDADES VALUES (1, 'PORTO ALEGRE', 01, DATE '1772-03-26', 'CAPITAL');
INSERT INTO TF_CIDADES VALUES (2, 'CAXIAS DO SUL', 01, DATE '1890-06-20', 'SERRA');
INSERT INTO TF_CIDADES VALUES (3, 'NOVO HAMBURGO', 01, DATE '1927-04-05', 'CAPITAL');
INSERT INTO TF_CIDADES VALUES (4, 'PELOTAS', 01, DATE '1758-06-18', 'INTERIOR');
INSERT INTO TF_CIDADES VALUES (5, 'SANTA CRUZ DO SUL', 01, DATE '1877-03-31', 'INTERIOR');

select * from TF_CIDADES
order by ID_CIDADE;


-- TIMES
CREATE TABLE TF_TIMES 
(
   ID_TIME NUMBER (2) NOT NULL,
   NOME VARCHAR (50) NOT NULL,
   ID_CIDADE NUMBER (2) NOT NULL,
   DATA_FUNDACAO DATE NOT NULL,
   TECNICO VARCHAR (20) NOT NULL,
   
   CONSTRAINT PK_TF_TIMES PRIMARY KEY (ID_TIME),
   CONSTRAINT AK_TF_TIMES UNIQUE (NOME),
   CONSTRAINT FK_TIME_CID FOREIGN KEY (ID_CIDADE) REFERENCES TF_CIDADES (ID_CIDADE)
)

INSERT INTO TIMES VALUES (1, 'GREMIO', 01, DATE '1903-09-15', 'RENATO PORTALUPPI');
INSERT INTO TIMES VALUES (2, 'INTERNACIONAL', 01, DATE '1909-04-04', 'ODAIR HELLMANN');
INSERT INTO TIMES VALUES (3, 'JUVENTUDE', 02, DATE '1913-06-29', 'JULINHO CAMARGO');
INSERT INTO TIMES VALUES (4, 'NOVO HAMBURGO', 03, DATE '1911-01-01', 'BENHUR PEREIRA');
INSERT INTO TIMES VALUES (5, 'CAXIAS', 02, DATE '1935-04-10', 'LUIZ CARLOS WINCK');

select * from times
order by idtime;


-- JOGOS
CREATE TABLE TF_JOGOS
(
   ID_JOGO NUMBER (4) NOT NULL,
   ID_TIME1 NUMBER (2) NOT NULL,
   ID_TIME2 NUMBER (2) NOT NULL,
   DATA_JOGO DATE NOT NULL,
   GOLS_TIME1 NUMBER (2) NOT NULL,
   GOLS_TIME2 NUMBER (2) NOT NULL,
   VENCEDOR NUMBER (2) NOT NULL,
   
   CONSTRAINT PK_JOGOS PRIMARY KEY (ID_JOGO),
)

INSERT INTO JOGOS VALUES (0001, 01, 02, DATE '2018-06-24', 05, 05,'');
INSERT INTO JOGOS VALUES (0002, 03, 04, DATE '2018-06-17', 01, 03,'');
INSERT INTO JOGOS VALUES (0003, 05, 01, DATE '2018-06-10', 02, 01,'');
INSERT INTO JOGOS VALUES (0004, 02, 03, DATE '2018-06-03', 00, 00,'');
INSERT INTO JOGOS VALUES (0005, 04, 05, DATE '2018-05-05', 04, 03,'');

select * from jogos
order by datajogo;
