-- ESTADOS
INSERT INTO TF_ESTADOS VALUES (1,    'ACRE',                'AC',    'NORTE');
INSERT INTO TF_ESTADOS VALUES (2,    'ALAGOAS',             'AL',    'NORDESTE');
INSERT INTO TF_ESTADOS VALUES (3,    'AMAPÁ',               'AP',    'NORTE');
INSERT INTO TF_ESTADOS VALUES (4,    'AMAZONAS',            'AM',    'NORTE');
INSERT INTO TF_ESTADOS VALUES (5,    'BAHIA',               'BA',    'NORDESTE');
INSERT INTO TF_ESTADOS VALUES (6,    'CEARÁ',               'CE',    'NORDESTE');
INSERT INTO TF_ESTADOS VALUES (7,    'DISTRITO FEDERAL',    'DF',    'CENTRO-OESTE');
INSERT INTO TF_ESTADOS VALUES (8,    'ESPÍRITO SANTO',      'ES',    'SUDESTE');
INSERT INTO TF_ESTADOS VALUES (9,    'GOIÁS',               'GO',    'CENTRO-OESTE');
INSERT INTO TF_ESTADOS VALUES (10,   'MARANHÃO',            'MA',    'NORDESTE');
INSERT INTO TF_ESTADOS VALUES (11,   'MATO GROSSO',         'MT',    'CENTRO-OESTE');
INSERT INTO TF_ESTADOS VALUES (12,   'MATO GROSSO DO SUL',  'MS',    'CENTRO-OESTE');
INSERT INTO TF_ESTADOS VALUES (13,   'MINAS GERAIS',        'MG',    'SUDESTE');
INSERT INTO TF_ESTADOS VALUES (14,   'PARÁ',                'PA',    'NORTE');
INSERT INTO TF_ESTADOS VALUES (15,   'PARAÍBA',             'PB',    'NORDESTE');
INSERT INTO TF_ESTADOS VALUES (16,   'PARANÁ',              'PR',    'SUL');
INSERT INTO TF_ESTADOS VALUES (17,   'PERNAMBUCO',          'PE',    'NORDESTE');
INSERT INTO TF_ESTADOS VALUES (18,   'PIAUÍ',               'PI',    'NORDESTE');
INSERT INTO TF_ESTADOS VALUES (19,   'RIO DE JANEIRO',      'RJ',    'SUDESTE');
INSERT INTO TF_ESTADOS VALUES (20,   'RIO GRANDE DO NORTE', 'RN',    'NORDESTE');
INSERT INTO TF_ESTADOS VALUES (21,   'RIO GRANDE DO SUL',   'RS',    'SUL');
INSERT INTO TF_ESTADOS VALUES (22,   'RONDÔNIA',            'RO',    'NORTE');
INSERT INTO TF_ESTADOS VALUES (23,   'RORAIMA',             'RR',    'NORTE');
INSERT INTO TF_ESTADOS VALUES (24,   'SANTA CATARINA',      'SC',    'SUL');
INSERT INTO TF_ESTADOS VALUES (25,   'SÃO PAULO',           'SP',    'SUDESTE');
INSERT INTO TF_ESTADOS VALUES (26,   'SERGIPE',             'SE',    'NORDESTE');
INSERT INTO TF_ESTADOS VALUES (27,   'TOCANTINS',           'TO',    'NORTE');

-- CIDADES
INSERT INTO TF_CIDADES VALUES (1, 'PORTO ALEGRE',      20,  DATE '1772-03-26', 'CAPITAL');
INSERT INTO TF_CIDADES VALUES (2, 'CAXIAS DO SUL',     20,  DATE '1890-06-20', 'SERRA');
INSERT INTO TF_CIDADES VALUES (3, 'NOVO HAMBURGO',     20,  DATE '1927-04-05', 'CAPITAL');
INSERT INTO TF_CIDADES VALUES (4, 'PELOTAS',           20,  DATE '1758-06-18', 'INTERIOR');
INSERT INTO TF_CIDADES VALUES (5, 'SANTA CRUZ DO SUL', 20,  DATE '1877-03-31', 'INTERIOR');

-- TIMES
INSERT INTO TF_TIMES VALUES (1, 'GREMIO', 1, DATE '1903-09-15', 'RENATO PORTALUPPI');
INSERT INTO TF_TIMES VALUES (2, 'INTERNACIONAL', 1, DATE '1909-04-04', 'ODAIR HELLMANN');
INSERT INTO TF_TIMES VALUES (3, 'JUVENTUDE', 2, DATE '1913-06-29', 'JULINHO CAMARGO');
INSERT INTO TF_TIMES VALUES (4, 'NOVO HAMBURGO', 3, DATE '1911-01-01', 'BENHUR PEREIRA');
INSERT INTO TF_TIMES VALUES (5, 'CAXIAS', 2, DATE '1935-04-10', 'LUIZ CARLOS WINCK');

-- JOGADORES
INSERT INTO TF_JOGADORES VALUES (1, 'PEDRO GEROMEL', DATE '1990-02-10', 1, 'ZAGUEIRO', NULL);
INSERT INTO TF_JOGADORES VALUES (2, 'MARCELO GROHE', DATE '1985-10-02', 1, 'GOLEIRO', NULL);
INSERT INTO TF_JOGADORES VALUES (3, 'LUAN', DATE '1987-11-07', 1, 'ATACANTE', NULL);
INSERT INTO TF_JOGADORES VALUES (4, 'JAEL', DATE '1984-03-26', 1, 'ATACANTE', NULL);
INSERT INTO TF_JOGADORES VALUES (5, 'BRESSAN', DATE '1989-08-15', 1, 'ZAGUEIRO', NULL);

-- JOGOS
INSERT INTO TF_JOGOS VALUES (1, 1, 5, 2, 5, DATE '2018-06-24');
INSERT INTO TF_JOGOS VALUES (2, 3, 1, 4, 3, DATE '2018-06-17');
INSERT INTO TF_JOGOS VALUES (3, 5, 2, 1, 1, DATE '2018-06-10');
INSERT INTO TF_JOGOS VALUES (4, 2, 0, 3, 0, DATE '2018-06-03');
INSERT INTO TF_JOGOS VALUES (5, 4, 4, 5, 3, DATE '2018-05-05');
