-- SELECIONA TODOS OS ESTADOS
SELECT * FROM TF_ESTADOS
ORDER BY ID_ESTADO;

-- SELECIONA TODAS AS CIDADES
SELECT * FROM TF_CIDADES
ORDER BY ID_CIDADE;

-- SELECIONA TODOS OS TIMES
SELECT * FROM TF_TIMES
ORDER BY ID_TIME;

-- SELECIONA TODOS OS JOGADORES
SELECT * FROM TF_JOGADORES
ORDER BY ID_JOGADOR;

-- SELECIONA TODOS OS JOGOS
SELECT * FROM TF_JOGOS
ORDER BY DATA;